name: build-deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Discord-Job
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Build
      run: |
         cd webhook/job
         go build -v cmd/k8s-status-discord-bot/main.go
         cd ../..
      
    - name: Build
      run: |
         cd bot/api
         go build -v cmd/k8s-status-discord-bot/main.go
         cd ../..
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Job to Docker Hub
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        context: ./webhook/job
        file: ./webhook/job/Dockerfile
        push: true 
        tags: horvatic/k8s-status-discord-bot-job:latest

    - name: Push Api to Docker Hub
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        context: ./bot/api
        file: ./bot/api/Dockerfile
        push: true 
        tags: horvatic/k8s-status-discord-bot-api:latest

    - name: Push Ui to Docker Hub
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        context: ./bot/ui
        file: ./bot/ui/Dockerfile
        push: true 
        tags: horvatic/k8s-status-discord-bot-ui:latest

